services:
  mysql:
    container_name: some-mysql
    platform: linux/amd64
    image: mysql:5.7
    restart: unless-stopped
    env_file:
      - ./env/mysql.env
    networks:
      - prestashop_network #crea su propia network
    volumes: #trabaja con dos volumenes
      - dbdata:/var/lib/mysql #creamos la carpeta para que no se pierda
      - dbdata:/var/lib/mysql # estio sirve para que los datos no se pierdan al reiniciar el contenedor
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:latest
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8080:80
    env_file:
      - ./env/prestashop.env
    networks:
      - prestashop_network
    volumes:
      - type: bind
        source: ./modules/testModule # fiormato a la pagina, debes crear la carpteta
        target: /var/www/html/modules/testModule # path to be mounted in the container
      - type: bind
        source: ./themes/myTheme # local path to the theme
        target:  /var/www/html/themes/myTheme # path to be mounted in the container
      - psdata:/var/www/html #tambien hay que crear la carpeta
      - ./sdata:/var/www/html #esto es para que todo tambien este en local
networks:
  prestashop_network:
volumes:
  psdata: 
  dbdata: #cada que creamos uno, aqui se ingresa
